# Generated by Django 5.1.3 on 2024-11-10 11:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_docenteuser_estudianteuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Atencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                ("profesional", models.CharField(max_length=100)),
                ("valoracion", models.TextField(blank=True, null=True)),
                ("diagnostico", models.TextField(blank=True, null=True)),
                ("intervenciones", models.TextField(blank=True, null=True)),
                ("ultima_edicion", models.DateTimeField(auto_now=True)),
                ("usuario_edicion", models.CharField(max_length=100)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atenciones",
                        to="api.paciente",
                    ),
                ),
            ],
        ),
    ]
