# Generated by Django 5.1.3 on 2024-11-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_atencion_options_alter_fichaclinica_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fichaclinica",
            name="atencion",
        ),
        migrations.AddField(
            model_name="fichaclinica",
            name="profesional",
            field=models.CharField(default="default", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fichaclinica",
            name="fecha_creacion",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name="Atencion",
        ),
    ]
