# Generated by Django 5.1.3 on 2024-11-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_fichaclinica_atencion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fichaclinica",
            name="hora_creacion",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="fichaclinica",
            name="hora_modificacion",
            field=models.TimeField(),
        ),
    ]
