# Generated by Django 5.1.3 on 2024-11-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_fichaclinica_hora_creacion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historialmodificacionfichaclinica",
            name="ficha_clinica",
        ),
        migrations.RemoveField(
            model_name="historialmodificacionfichaclinica",
            name="usuario",
        ),
        migrations.DeleteModel(
            name="FichaClinica",
        ),
        migrations.DeleteModel(
            name="HistorialModificacionFichaClinica",
        ),
    ]
