# Generated by Django 5.1.3 on 2024-11-13 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_historialmodificacionfichaclinica_ficha_clinica_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FichaClinica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                ("motivo_consulta", models.TextField()),
                ("anamnesis", models.TextField()),
                ("examen_fisico", models.TextField()),
                ("diagnostico", models.TextField()),
                ("intervenciones", models.TextField()),
                ("factores", models.TextField()),
                ("rau_necesidades", models.TextField()),
                ("instrumentos_aplicados", models.TextField()),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fichas_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fichas",
                        to="api.paciente",
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fichas_modificadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ficha Clínica",
                "verbose_name_plural": "Fichas Clínicas",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
